- id: texcleanup
  name: texcleanup
  description: Run texcleanup
  minimum_pre_commit_version: 2.1.0
  entry: texcleanup
  language: python
  types: [tex]
- id: texindent
  name: texindent
  description: Run texindent
  minimum_pre_commit_version: 2.1.0
  entry: texindent
  language: conda
  types: [tex]
