sphinx:
  configuration: docs/conf.py

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: environment.yaml

python:
  install:
  - method: pip
    path: .
  system_packages: true
